name: Pylint

on: [push]

jobs:
  build:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        uses: veertuinc/anka-vm-github-action@v1.3.3
        with:
          anka-vm-template-name: "anka-packer-base-macos"
          anka-vm-tag-name: "veertu-registry-push-test"
          anka-run-options: "--env"
          vm-commands: |
            echo \"Starting build process on \$(hostname)\"
            ./build.sh && \
            ./cleanup.sh
          anka-cp-host-paths: |
            ./
            /Users/ec2-user/cache
          artifact-files: |
            log.txt
            build/binaryfile-v1
