name: Pylint

on: [push]

jobs:
  build-1:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: build-1
        id: build
        uses: veertuinc/anka-vm-github-action@v1.3.3
        with:
          anka-vm-template-name: "6706ab3e-7aa4-42a5-88ae-931928236afc"
          #anka-vm-tag-name: "veertu-registry-push-test"
          anka-run-options: "--env"
          vm-commands: |
            echo \"Starting build process on \$(hostname)\"
            echo \"This is a test $(whoami)\"
  build-2:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: build-2
        id: build
        uses: veertuinc/anka-vm-github-action@v1.3.3
        with:
          anka-vm-template-name: "6706ab3e-7aa4-42a5-88ae-931928236afc"
          #anka-vm-tag-name: "veertu-registry-push-test"
          anka-run-options: "--env"
          vm-commands: |
            echo \"Starting build process on \$(hostname)\"
            echo \"This is a test $(whoami)\"
